drop table if exists item CASCADE;
create table item
(
    id        bigint generated by default as identity,
    item_name varchar(10),
    price     integer,
    quantity  integer,
    primary key (id)
);
-- 테스트 시작할 때 테이블을 만들어 주는 sql을 넣을 수 있다.